project:
  type: book
  output-dir: docs

book:
  title: "R for Bio Data Science"
  reader-mode: true
  page-navigation: true

  page-footer:
    left: |
      R for Bio Data Science
    center: |
      All content Â© 2023 - 2024 Leon Eyrich Jessen. All rights reserved
    right: |
      Full course description available at <a href="https://kurser.dtu.dk/course/22100">DTU Course Base</a>.
  
  cover-image: images/r4bds_logo_v2.png
  
  chapters:
    - index.qmd
    - prologue.qmd
    - getting_started.qmd
    
    - part: lab00.qmd
      chapters:
        - lab01.qmd
        - lab02.qmd
        - lab03.qmd
        - lab04.qmd
        - lab05.qmd
        - lab06.qmd
        - lab07.qmd
        - lab08.qmd
        - lab09.qmd
        - lab10.qmd

    - part: resources.qmd
      chapters: 
        - guide_for_working_locally.qmd
        - guide_for_building_r4ds2e_locally.qmd
        - paths_and_projects.qmd
        - variable_assignment_in_r.qmd
        - code_styling.qmd
        - primer_on_linear_models_in_r.qmd
        - external_resources.qmd

    - part: course_elements.qmd
      chapters: 
        - assignments.qmd
        - project_description.qmd
        - project_faq.qmd
        - project_checklist.qmd
        - exam.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mainfont: avenir
    fontsize: 18px

editor: source

